# Generated by Django 4.1.4 on 2023-03-01 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='paid_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, verbose_name='Выплаченные курсы'),
        ),
    ]
